### ISSUE TITLE
when delete a key, return invalid value

### ISSUE THREAD

**Issue by fiefdx** [flike/idgo#6]
**In redis delete a key:**
```
127.0.0.1:6379> del a
(integer) 1
```

**In idgo delete a key:**
```
127.0.0.1:6389> del abc
OK
```

**I use python redis to connect idgo, when delete a key, I got a error:**
```
Traceback (most recent call last):
  File "./idgo_concurrent_test.py", line 82, in <module>
    r.delete("id_test")
  File "/usr/lib/python2.7/dist-packages/redis/client.py", line 841, in delete
    return self.execute_command('DEL', *names)
  File "/usr/lib/python2.7/dist-packages/redis/client.py", line 573, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/lib/python2.7/dist-packages/redis/client.py", line 587, in parse_response
    return self.response_callbacks[command_name](response, **options)
ValueError: invalid literal for int() with base 10: 'OK'
```

**Comment by flike** [comment]
yeah, idgo need return value 1，not ok. you can fix this bug :+1:

**Comment by flike** [comment]
fixed
